host = "127.0.0.1"
port = 7379
storage_path = "data"
engine = "rwlock"
sync_interval_seconds = 60

[replication]
enabled = false
mqtt_broker = "test.mosquitto.org"
mqtt_port = 1883
topic_prefix = "quickstart-merkle-kv"
client_id = "quickstart-node"
