host = "127.0.0.1"
port = 7379
storage_path = "data"
engine = "rwlock"
sync_interval_seconds = 60

[replication]
enabled = true
mqtt_broker = "test.mosquitto.org"
mqtt_port = 1883
topic_prefix = "merkle_kv_demo"
client_id = "demo_node"
client_password = "demo_password"
